apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  namespace: {{.Values.global.namespace}}
  labels:
    app: {{ include "mychart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mychart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mychart.name" . }}
    spec:
      containers:
        - name: identity-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.urls }}
          env:
            {{- range .Values.env}}
              - name: {{.name}}
                value: {{.value | quote}}
            {{- end}}
            {{- range .Values.secretENV}}
              - name: {{.name}}
                valueFrom:
                  secretKeyRef:
                    name: {{.secretName}}
                    key: {{.key}}
            {{- end}}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
