apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mychart.fullname" . }}
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: 
      - default
  selector:
    matchLabels:
      app: {{ include "mychart.name" . }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
