apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  namespace: {{.Values.global.namespace}}
  annotations:
    {{- range $key, $value := .Values.service.annotations}}
    {{$key}}: {{$value | quote}}
    {{- end}}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "mychart.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.urls }}