name: CI/CD todolist-deploy-frontend

on:
  push:
    branches:
      - dev
    # paths:
    #   - "Apps/Frontend/**"

jobs:
  build:
    name: Push to S3
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set environment variables
        id: set_env
        run: |
          BRANCH=${GITHUB_REF##*/}
          if [[ "$BRANCH" == "stag" ]]; then
            echo "ENV=stag" >> $GITHUB_ENV
          else
            echo "ENV=main" >> $GITHUB_ENV
          fi

      - name: Configure AWS credenticals
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}', env.ENV)]  }}
          aws-secret-access-key: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', env.ENV)]  }}
          aws-region: ap-southeast-1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
			
      - name: Install dependencies
        run: pip install boto3

      - name: Execute Frontend Deployment Script

        run: |
					chmod +x ./automation-scripts/python/deploy_frontend.py
					python ./automation-scripts/python/deploy_frontend.py ${{ secrets.S3_BUCKET_NAME }}

