name: CI/CD todolist-deploy-backend

on:
  push:
    branches:
      - dev
    paths:
      - "Apps/Backend/**"

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and Push Microservices with Custom Tags
        run: ./automation-scripts/bash/build_and_push.sh thanhphat0 1.0.0 1.0.0 1.0.0
