name: CI/CD todolist

on:
  push:
    branches:
      - stag
      - main

jobs:
  terraform:
    name: "Run terraform for ${{matrix.environment}}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [stag, main]
        include:
          - environment: stag
            directory: staging
          - environment: main
            directory: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credenticals
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}', matrix.environment)]  }}
          aws-secret-access-key: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', matrix.environment)]  }}
          aws-region: ap-southeast-1

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          working-directory: ./terraform

      - name: Terraform init
        run: terraform init
        working-directory: ./terraform/environments/${{matrix.directory}}

      - name: Export variables
        run: |
          export TF_VAR_db_password_task_service=${{secrets.DB_PASSWORD_TASK_SERVICE}}
          export TF_VAR_db_password_identity_service=${{secrets.DB_PASSWORD_IDENTITY_SERVICE}}
          export TF_VAR_db_username_task_service=${{secrets.DB_USERNAME_TASK_SERVICE}}
          export TF_VAR_db_username_identity_service=${{secrets.DB_USERNAME_IDENTITY_SERVICE}}
          export TF_VAR_create_certificate_for_domain=true
        shell: bash

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color > plan_output.txt
        working-directory: ./terraform/environments/${{matrix.directory}}
        continue-on-error: true

      - name: Check plan changes
        id: check_plan
        run: |
          if grep -q "No changes. Your infrastructure matches the configuration." plan_output.txt; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
        working-directory: ./terraform/environments/${{matrix.directory}}

      - name: Terraform apply
        if: steps.check_plan.outputs.has_changes == 'true'
        run: terraform apply --auto-approve
        working-directory: ./terraform/environments/${{matrix.directory}}

      - name: Save terraform ouputs
        id: output
        run: terraform output -json > ${{matrix.environment}}-terraform-output.json
        working-directory: ./terraform/environments/${{matrix.directory}}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.environment}}-tf-output
          path: ./terraform/environments/${{matrix.directory}}/${{matrix.environment}}-terraform-output.json

  helm:
    name: "Deploy Helm Charts to EKS"
    runs-on: ubuntu-latest
    needs: terraform
    strategy:
      matrix:
        environment: [stag, main]
        include:
          - environment: stag
            file-name: values.stag.yaml
          - environment: main
            file-name: values.prod.yaml

    steps:
      - name: Checkout code
        uses: action/checkout@v4

      - name: Download terraform artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{matrix.environment}}-tf-output
          path: /tmp/tf-output

      - name: Extract variables from JSON
        id: tf-vars
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const env = JSON.parse(fs.readFileSync('/tmp/tf-output/${{ matrix.environment }}-terraform-output.json', 'utf8'));
            core.exportVariable('connection_string', env.identity_connection_string.value)
            core.exportVariable('task_connection_url', env.task_connection_url.value)
            core.exportVariable('eks-name', env.eks-name.value)
            core.exportVariable('aws_region', env.aws_region.value)

      - name: Configure AWS credenticals
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}', matrix.environment)]  }}
          aws-secret-access-key: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', matrix.environment)]  }}
          aws-region: ${{env.aws_region}}

      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{env.aws_region}} --name ${{ env.eks-name }}

      - name: Create secret in Kubernetes
        run: |
          kubectl create secret generic identity-db \
            --from-literal=connectionString=${{ env.connection_string }}
          kubectl create secret generic task-db \
            --from-literal=db-url=${{ env.task_connection_url }} \
            --from-literal=db-username=${{ secrets.DB_USERNAME_TASK_SERVICE }} \
            --from-literal=db-password=${{ secrets.DB_PASSWORD_TASK_SERVICE }}

      - name: Helm upgrade/install
        run: |
          helm upgrade --install todolist . -f ${{matrix.file-name}}
        working-directory: ./helm
